org: unikraft
name: sig-security
description: Unikraft Security Special Interest Group
privacy: closed

maintainers:
  - name: Hugo Lefeuvre
    github: hlef
  - name: Michalis Pappas
    github: michpappas
  - name: Vlad-Andrei Bădoiu
    github: vladandrew

reviewers:
  - name: Daniel Dincă
    github: danield20

repos:
  - name: lib-axtls
  - name: lib-libhogweed
  - name: lib-libsodium
  - name: lib-mbedtls
  - name: lib-openssl
