org: unikraft
name: sig-plat
description: Unikraft Platforms Special Interest Group
privacy: closed

maintainers:
  - name: Simon Kuenzer
    github: skuenzer
  - name: Marc Rittinghaus
    github: marcrittinghaus

reviewers:
  - name: Daniel Dincă
    github: danield20
  - name: Andra Paraschiv
    github: andraprs

repos:
  - name: plat-aws
  - name: plat-digitalocean
  - name: plat-firecracker
  - name: plat-gcp
  - name: plat-solo5
